import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Dashboard from "../components/Dashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZySync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505] text-white`}
      >
        <div className='h-screen'>
          {/* now this is the real page which come after loading now for this it will first check with the user has login or not  */}
          <Dashboard/>
          {children}
        </div>
      </body>
    </html>
  );
}
